[package]
name = "onnx"
version = "0.1.0"
edition = "2021"

[features]
default = []
coreml = ["ort/coreml"]
directml = ["ort/directml"]

[dependencies]
ndarray = "0.16"

[target.'cfg(debug_assertions)'.dependencies]
ort = { version = "=2.0.0-rc.10", features = ["ndarray", "load-dynamic"] }

[target.'cfg(not(debug_assertions))'.dependencies]
ort = { version = "=2.0.0-rc.10", features = ["ndarray"] }
