[package]
name = "owhisper-config"
version = "0.0.1"
edition = "2024"

[dependencies]
config = { version = "0.15.13" }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
